
var ortWasm = (function() {
  var _scriptDir = typeof document !== 'undefined' && document.currentScript ? document.currentScript.src : undefined;
  if (typeof __filename !== 'undefined') _scriptDir = _scriptDir || __filename;
  return (
function(ortWasm) {
  ortWasm = ortWasm || {};


var d;d||(d=typeof ortWasm !== 'undefined' ? ortWasm : {});var aa,ba;d.ready=new Promise(function(a,b){aa=a;ba=b});var g={},m;for(m in d)d.hasOwnProperty(m)&&(g[m]=d[m]);var ca="./this.program",da="object"===typeof window,p="function"===typeof importScripts,ea="object"===typeof process&&"object"===typeof process.versions&&"string"===typeof process.versions.node,r="",fa,v,w,x,z;
if(ea)r=p?require("path").dirname(r)+"/":__dirname+"/",fa=function(a,b){x||(x=require("fs"));z||(z=require("path"));a=z.normalize(a);return x.readFileSync(a,b?null:"utf8")},w=function(a){a=fa(a,!0);a.buffer||(a=new Uint8Array(a));a.buffer||A("Assertion failed: undefined");return a},v=function(a,b,c){x||(x=require("fs"));z||(z=require("path"));a=z.normalize(a);x.readFile(a,function(e,h){e?c(e):b(h.buffer)})},1<process.argv.length&&(ca=process.argv[1].replace(/\\/g,"/")),process.argv.slice(2),process.on("uncaughtException",
function(a){throw a;}),process.on("unhandledRejection",A),d.inspect=function(){return"[Emscripten Module object]"};else if(da||p)p?r=self.location.href:"undefined"!==typeof document&&document.currentScript&&(r=document.currentScript.src),_scriptDir&&(r=_scriptDir),0!==r.indexOf("blob:")?r=r.substr(0,r.lastIndexOf("/")+1):r="",fa=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.send(null);return b.responseText},p&&(w=function(a){var b=new XMLHttpRequest;b.open("GET",a,!1);b.responseType="arraybuffer";
b.send(null);return new Uint8Array(b.response)}),v=function(a,b,c){var e=new XMLHttpRequest;e.open("GET",a,!0);e.responseType="arraybuffer";e.onload=function(){200==e.status||0==e.status&&e.response?b(e.response):c()};e.onerror=c;e.send(null)};var ha=d.print||console.log.bind(console),B=d.printErr||console.warn.bind(console);for(m in g)g.hasOwnProperty(m)&&(d[m]=g[m]);g=null;d.thisProgram&&(ca=d.thisProgram);var C;d.wasmBinary&&(C=d.wasmBinary);var noExitRuntime=d.noExitRuntime||!1;
"object"!==typeof WebAssembly&&A("no native wasm support detected");var ia,ja=!1,ka="undefined"!==typeof TextDecoder?new TextDecoder("utf8"):void 0;
function la(a,b,c){var e=b+c;for(c=b;a[c]&&!(c>=e);)++c;if(16<c-b&&a.subarray&&ka)return ka.decode(a.subarray(b,c));for(e="";b<c;){var h=a[b++];if(h&128){var k=a[b++]&63;if(192==(h&224))e+=String.fromCharCode((h&31)<<6|k);else{var l=a[b++]&63;h=224==(h&240)?(h&15)<<12|k<<6|l:(h&7)<<18|k<<12|l<<6|a[b++]&63;65536>h?e+=String.fromCharCode(h):(h-=65536,e+=String.fromCharCode(55296|h>>10,56320|h&1023))}}else e+=String.fromCharCode(h)}return e}function D(a,b){return a?la(E,a,b):""}
function ma(a,b,c,e){if(!(0<e))return 0;var h=c;e=c+e-1;for(var k=0;k<a.length;++k){var l=a.charCodeAt(k);if(55296<=l&&57343>=l){var u=a.charCodeAt(++k);l=65536+((l&1023)<<10)|u&1023}if(127>=l){if(c>=e)break;b[c++]=l}else{if(2047>=l){if(c+1>=e)break;b[c++]=192|l>>6}else{if(65535>=l){if(c+2>=e)break;b[c++]=224|l>>12}else{if(c+3>=e)break;b[c++]=240|l>>18;b[c++]=128|l>>12&63}b[c++]=128|l>>6&63}b[c++]=128|l&63}}b[c]=0;return c-h}
function na(a){for(var b=0,c=0;c<a.length;++c){var e=a.charCodeAt(c);55296<=e&&57343>=e&&(e=65536+((e&1023)<<10)|a.charCodeAt(++c)&1023);127>=e?++b:b=2047>=e?b+2:65535>=e?b+3:b+4}return b}function oa(a){var b=na(a)+1,c=pa(b);c&&ma(a,F,c,b);return c}var qa,F,E,G,H,J;
function ra(){var a=ia.buffer;qa=a;d.HEAP8=F=new Int8Array(a);d.HEAP16=new Int16Array(a);d.HEAP32=G=new Int32Array(a);d.HEAPU8=E=new Uint8Array(a);d.HEAPU16=new Uint16Array(a);d.HEAPU32=H=new Uint32Array(a);d.HEAPF32=J=new Float32Array(a);d.HEAPF64=new Float64Array(a)}var sa,ta=[],ua=[],va=[],wa=[];function xa(){var a=d.preRun.shift();ta.unshift(a)}var K=0,ya=null,L=null;d.preloadedImages={};d.preloadedAudios={};
function A(a){if(d.onAbort)d.onAbort(a);B(a);ja=!0;a=new WebAssembly.RuntimeError("abort("+a+"). Build with -s ASSERTIONS=1 for more info.");ba(a);throw a;}function za(){return M.startsWith("data:application/octet-stream;base64,")}var M;M="ort-wasm.wasm";if(!za()){var Aa=M;M=d.locateFile?d.locateFile(Aa,r):r+Aa}function Ba(){var a=M;try{if(a==M&&C)return new Uint8Array(C);if(w)return w(a);throw"both async and sync fetching of the wasm failed";}catch(b){A(b)}}
function Ca(){if(!C&&(da||p)){if("function"===typeof fetch&&!M.startsWith("file://"))return fetch(M,{credentials:"same-origin"}).then(function(a){if(!a.ok)throw"failed to load wasm binary file at '"+M+"'";return a.arrayBuffer()}).catch(function(){return Ba()});if(v)return new Promise(function(a,b){v(M,function(c){a(new Uint8Array(c))},b)})}return Promise.resolve().then(function(){return Ba()})}
function Da(a){for(;0<a.length;){var b=a.shift();if("function"==typeof b)b(d);else{var c=b.sb;"number"===typeof c?void 0===b.ib?sa.get(c)():sa.get(c)(b.ib):c(void 0===b.ib?null:b.ib)}}}function Ea(a){this.kb=a-16;this.Cb=function(b){G[this.kb+4>>2]=b};this.zb=function(b){G[this.kb+8>>2]=b};this.Ab=function(){G[this.kb>>2]=0};this.yb=function(){F[this.kb+12>>0]=0};this.Bb=function(){F[this.kb+13>>0]=0};this.ub=function(b,c){this.Cb(b);this.zb(c);this.Ab();this.yb();this.Bb()}}
var Fa=0,Ga={},Ha=[null,[],[]],N={},O;O=ea?function(){var a=process.hrtime();return 1E3*a[0]+a[1]/1E6}:function(){return performance.now()};var Ia=["explicit","same-upper","same-lower"],Ja=["oihw","hwio","ohwi","ihwo"],Ka=["nchw","nhwc"],La="float32 float16 int32 uint32 int8 uint8".split(" ");function P(a,b){if(0!==a&&0!==b){for(var c=[],e=0;e<a;++e,b+=4)c.push(G[b>>2]);return c}}
function Ma(a,b="float32"){const c=G[a>>2]+H[a+8>>2];a=H[a+4>>2];"float32"===b||A("Assertion failed: undefined");return new Float32Array(E.buffer,c,a/Float32Array.BYTES_PER_ELEMENT)}function Na(a){return{type:La[H[a>>2]],dimensions:P(H[a+8>>2],G[a+4>>2])}}function Oa(a){return{windowDimensions:P(H[a>>2],G[a+4>>2]),padding:"explicit"===Ia[G[a+32>>2]]?P(H[a+8>>2],G[a+12>>2]):void 0,strides:P(H[a+16>>2],G[a+20>>2]),dilations:P(H[a+24>>2],G[a+28>>2]),autoPad:Ia[G[a+32>>2]],layout:Ka[G[a+36>>2]]}}
var Q,S,T,U,V,W,X,Y,Pa={};function Qa(){if(!Ra){var a={USER:"web_user",LOGNAME:"web_user",PATH:"/",PWD:"/",HOME:"/home/web_user",LANG:("object"===typeof navigator&&navigator.languages&&navigator.languages[0]||"C").replace("-","_")+".UTF-8",_:ca||"./this.program"},b;for(b in Pa)void 0===Pa[b]?delete a[b]:a[b]=Pa[b];var c=[];for(b in a)c.push(b+"="+a[b]);Ra=c}return Ra}var Ra;
function Sa(a,b){a=new Date(1E3*G[a>>2]);G[b>>2]=a.getUTCSeconds();G[b+4>>2]=a.getUTCMinutes();G[b+8>>2]=a.getUTCHours();G[b+12>>2]=a.getUTCDate();G[b+16>>2]=a.getUTCMonth();G[b+20>>2]=a.getUTCFullYear()-1900;G[b+24>>2]=a.getUTCDay();G[b+36>>2]=0;G[b+32>>2]=0;G[b+28>>2]=(a.getTime()-Date.UTC(a.getUTCFullYear(),0,1,0,0,0,0))/864E5|0;Sa.rb||(Sa.rb=oa("GMT"));G[b+40>>2]=Sa.rb;return b}
function Ta(){function a(l){return(l=l.toTimeString().match(/\(([A-Za-z ]+)\)$/))?l[1]:"GMT"}if(!Ua){Ua=!0;var b=(new Date).getFullYear(),c=new Date(b,0,1),e=new Date(b,6,1);b=c.getTimezoneOffset();var h=e.getTimezoneOffset(),k=Math.max(b,h);G[Va()>>2]=60*k;G[Wa()>>2]=Number(b!=h);c=a(c);e=a(e);c=oa(c);e=oa(e);h<b?(G[Z()>>2]=c,G[Z()+4>>2]=e):(G[Z()>>2]=e,G[Z()+4>>2]=c)}}var Ua;function $a(a){return 0===a%4&&(0!==a%100||0===a%400)}function ab(a,b){for(var c=0,e=0;e<=b;c+=a[e++]);return c}
var bb=[31,29,31,30,31,30,31,31,30,31,30,31],cb=[31,28,31,30,31,30,31,31,30,31,30,31];function db(a,b){for(a=new Date(a.getTime());0<b;){var c=a.getMonth(),e=($a(a.getFullYear())?bb:cb)[c];if(b>e-a.getDate())b-=e-a.getDate()+1,a.setDate(1),11>c?a.setMonth(c+1):(a.setMonth(0),a.setFullYear(a.getFullYear()+1));else{a.setDate(a.getDate()+b);break}}return a}
function eb(a,b,c,e){function h(f,n,q){for(f="number"===typeof f?f.toString():f||"";f.length<n;)f=q[0]+f;return f}function k(f,n){return h(f,n,"0")}function l(f,n){function q(Xa){return 0>Xa?-1:0<Xa?1:0}var I;0===(I=q(f.getFullYear()-n.getFullYear()))&&0===(I=q(f.getMonth()-n.getMonth()))&&(I=q(f.getDate()-n.getDate()));return I}function u(f){switch(f.getDay()){case 0:return new Date(f.getFullYear()-1,11,29);case 1:return f;case 2:return new Date(f.getFullYear(),0,3);case 3:return new Date(f.getFullYear(),
0,2);case 4:return new Date(f.getFullYear(),0,1);case 5:return new Date(f.getFullYear()-1,11,31);case 6:return new Date(f.getFullYear()-1,11,30)}}function R(f){f=db(new Date(f.gb+1900,0,1),f.pb);var n=new Date(f.getFullYear()+1,0,4),q=u(new Date(f.getFullYear(),0,4));n=u(n);return 0>=l(q,f)?0>=l(n,f)?f.getFullYear()+1:f.getFullYear():f.getFullYear()-1}var y=G[e+40>>2];e={Fb:G[e>>2],Eb:G[e+4>>2],nb:G[e+8>>2],lb:G[e+12>>2],hb:G[e+16>>2],gb:G[e+20>>2],ob:G[e+24>>2],pb:G[e+28>>2],Nb:G[e+32>>2],Db:G[e+
36>>2],Gb:y?D(y):""};c=D(c);y={"%c":"%a %b %d %H:%M:%S %Y","%D":"%m/%d/%y","%F":"%Y-%m-%d","%h":"%b","%r":"%I:%M:%S %p","%R":"%H:%M","%T":"%H:%M:%S","%x":"%m/%d/%y","%X":"%H:%M:%S","%Ec":"%c","%EC":"%C","%Ex":"%m/%d/%y","%EX":"%H:%M:%S","%Ey":"%y","%EY":"%Y","%Od":"%d","%Oe":"%e","%OH":"%H","%OI":"%I","%Om":"%m","%OM":"%M","%OS":"%S","%Ou":"%u","%OU":"%U","%OV":"%V","%Ow":"%w","%OW":"%W","%Oy":"%y"};for(var t in y)c=c.replace(new RegExp(t,"g"),y[t]);var Ya="Sunday Monday Tuesday Wednesday Thursday Friday Saturday".split(" "),
Za="January February March April May June July August September October November December".split(" ");y={"%a":function(f){return Ya[f.ob].substring(0,3)},"%A":function(f){return Ya[f.ob]},"%b":function(f){return Za[f.hb].substring(0,3)},"%B":function(f){return Za[f.hb]},"%C":function(f){return k((f.gb+1900)/100|0,2)},"%d":function(f){return k(f.lb,2)},"%e":function(f){return h(f.lb,2," ")},"%g":function(f){return R(f).toString().substring(2)},"%G":function(f){return R(f)},"%H":function(f){return k(f.nb,
2)},"%I":function(f){f=f.nb;0==f?f=12:12<f&&(f-=12);return k(f,2)},"%j":function(f){return k(f.lb+ab($a(f.gb+1900)?bb:cb,f.hb-1),3)},"%m":function(f){return k(f.hb+1,2)},"%M":function(f){return k(f.Eb,2)},"%n":function(){return"\n"},"%p":function(f){return 0<=f.nb&&12>f.nb?"AM":"PM"},"%S":function(f){return k(f.Fb,2)},"%t":function(){return"\t"},"%u":function(f){return f.ob||7},"%U":function(f){var n=new Date(f.gb+1900,0,1),q=0===n.getDay()?n:db(n,7-n.getDay());f=new Date(f.gb+1900,f.hb,f.lb);return 0>
l(q,f)?k(Math.ceil((31-q.getDate()+(ab($a(f.getFullYear())?bb:cb,f.getMonth()-1)-31)+f.getDate())/7),2):0===l(q,n)?"01":"00"},"%V":function(f){var n=new Date(f.gb+1901,0,4),q=u(new Date(f.gb+1900,0,4));n=u(n);var I=db(new Date(f.gb+1900,0,1),f.pb);return 0>l(I,q)?"53":0>=l(n,I)?"01":k(Math.ceil((q.getFullYear()<f.gb+1900?f.pb+32-q.getDate():f.pb+1-q.getDate())/7),2)},"%w":function(f){return f.ob},"%W":function(f){var n=new Date(f.gb,0,1),q=1===n.getDay()?n:db(n,0===n.getDay()?1:7-n.getDay()+1);f=
new Date(f.gb+1900,f.hb,f.lb);return 0>l(q,f)?k(Math.ceil((31-q.getDate()+(ab($a(f.getFullYear())?bb:cb,f.getMonth()-1)-31)+f.getDate())/7),2):0===l(q,n)?"01":"00"},"%y":function(f){return(f.gb+1900).toString().substring(2)},"%Y":function(f){return f.gb+1900},"%z":function(f){f=f.Db;var n=0<=f;f=Math.abs(f)/60;return(n?"+":"-")+String("0000"+(f/60*100+f%60)).slice(-4)},"%Z":function(f){return f.Gb},"%%":function(){return"%"}};for(t in y)c.includes(t)&&(c=c.replace(new RegExp(t,"g"),y[t](e)));t=fb(c);
if(t.length>b)return 0;F.set(t,a);return t.length-1}(function(){function a(){return{jb:{},xb:1,create:function(b,c){c=c||{};var e=this.xb++;c.qb=1;c.object=b;this.jb[e]=c;return e},get:function(b){if(0!==b)return this.jb[b].object},mb:function(b){this.jb[b].qb++},release:function(b){var c=this.jb[b];c.qb--;0>=c.qb&&delete this.jb[b]}}}Q||(Q=Q||a(),S=S||a(),T=T||a(),U=U||a(),V=V||a(),W=W||a(),X=X||a(),Y=Y||a())})();function fb(a){var b=Array(na(a)+1);ma(a,b,0,b.length);return b}
var jb={a:function(a){return pa(a+16)+16},c:function(a,b){va.unshift({sb:a,ib:b})},f:function(a,b){va.unshift({sb:a,ib:b})},b:function(a,b,c){(new Ea(a)).ub(b,c);Fa++;throw a;},K:function(a,b){a=D(a);return N.Hb(a,b)},o:function(){return 0},R:function(){},L:function(){},r:function(){return 42},B:function(){return 0},M:function(){},Q:function(a,b){a=D(a);return N.Ib(a,b)},P:function(a,b,c,e,h,k){k<<=12;if(0!==(e&16)&&0!==a%65536)b=-28;else if(0!==(e&32)){a=65536*Math.ceil(b/65536);var l=gb(65536,a);
l?(E.fill(0,l,l+a),a=l):a=0;a?(Ga[a]={wb:a,vb:b,tb:!0,fd:h,Mb:c,flags:e,offset:k},b=a):b=-48}else b=-52;return b},N:function(a,b){var c=Ga[a];0!==b&&c?(b===c.vb&&(Ga[a]=null,c.tb&&hb(c.wb)),a=0):a=-28;return a},m:function(){},J:function(a,b,c){a=D(a);return N.Jb(a,b,c)},G:function(){},s:function(){},I:function(){},k:function(){A()},v:function(a,b){if(0===a)a=Date.now();else if(1===a||4===a)a=O();else return G[ib()>>2]=28,-1;G[b>>2]=a/1E3|0;G[b+4>>2]=a%1E3*1E6|0;return 0},H:function(a,b){return a-
b},za:function(){A("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},j:function(){A("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},Aa:function(){A("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},ya:function(){A("To use dlopen, you need to use Emscripten's linking support, see https://github.com/emscripten-core/emscripten/wiki/Linking")},
S:function(){return 2147483648},A:function(a,b,c){E.copyWithin(a,b,b+c)},l:function(a){var b=E.length;a>>>=0;if(2147483648<a)return!1;for(var c=1;4>=c;c*=2){var e=b*(1+.2/c);e=Math.min(e,a+100663296);e=Math.max(a,e);0<e%65536&&(e+=65536-e%65536);a:{try{ia.grow(Math.min(2147483648,e)-qa.byteLength+65535>>>16);ra();var h=1;break a}catch(k){}h=void 0}if(h)return!0}return!1},F:function(a){for(var b=O();O()-b<a;);},wa:function(a){var b={devicePreference:"default",powerPreference:"default"},c=["default",
"gpu","cpu"],e=["default","high-performance","low-power"];0!==a&&(b={devicePreference:c[H[a>>2]],powerPreference:e[H[a+4>>2]]});return Q.create(navigator.ml.createContext(b))},D:function(a,b){var c=0;Qa().forEach(function(e,h){var k=b+c;h=G[a+4*h>>2]=k;for(k=0;k<e.length;++k)F[h++>>0]=e.charCodeAt(k);F[h>>0]=0;c+=e.length+1});return 0},E:function(a,b){var c=Qa();G[a>>2]=c.length;var e=0;c.forEach(function(h){e+=h.length+1});G[b>>2]=e;return 0},i:function(){return 0},C:function(a,b){a=1==a||2==a?2:
A();F[b>>0]=a;return 0},p:function(a,b,c,e){a=N.Lb(a);b=N.Kb(a,b,c);G[e>>2]=b;return 0},z:function(){},q:function(a,b,c,e){for(var h=0,k=0;k<c;k++){for(var l=G[b+8*k>>2],u=G[b+(8*k+4)>>2],R=0;R<u;R++){var y=E[l+R],t=Ha[a];0===y||10===y?((1===a?ha:B)(la(t,0)),t.length=0):t.push(y)}h+=u}G[e>>2]=h;return 0},ca:function(a){var b=Date.now();G[a>>2]=b/1E3|0;G[a+4>>2]=b%1E3*1E3|0;return 0},O:Sa,t:function(a,b){Ta();a=new Date(1E3*G[a>>2]);G[b>>2]=a.getSeconds();G[b+4>>2]=a.getMinutes();G[b+8>>2]=a.getHours();
G[b+12>>2]=a.getDate();G[b+16>>2]=a.getMonth();G[b+20>>2]=a.getFullYear()-1900;G[b+24>>2]=a.getDay();var c=new Date(a.getFullYear(),0,1);G[b+28>>2]=(a.getTime()-c.getTime())/864E5|0;G[b+36>>2]=-(60*a.getTimezoneOffset());var e=(new Date(a.getFullYear(),6,1)).getTimezoneOffset();c=c.getTimezoneOffset();a=(e!=c&&a.getTimezoneOffset()==Math.min(c,e))|0;G[b+32>>2]=a;a=G[Z()+(a?4:0)>>2];G[b+40>>2]=a;return b},n:function(a){Ta();var b=new Date(G[a+20>>2]+1900,G[a+16>>2],G[a+12>>2],G[a+8>>2],G[a+4>>2],G[a>>
2],0),c=G[a+32>>2],e=b.getTimezoneOffset(),h=new Date(b.getFullYear(),0,1),k=(new Date(b.getFullYear(),6,1)).getTimezoneOffset(),l=h.getTimezoneOffset(),u=Math.min(l,k);0>c?G[a+32>>2]=Number(k!=l&&u==e):0<c!=(u==e)&&(k=Math.max(l,k),b.setTime(b.getTime()+6E4*((0<c?u:k)-e)));G[a+24>>2]=b.getDay();G[a+28>>2]=(b.getTime()-h.getTime())/864E5|0;G[a>>2]=b.getSeconds();G[a+4>>2]=b.getMinutes();G[a+8>>2]=b.getHours();G[a+12>>2]=b.getDate();G[a+16>>2]=b.getMonth();return b.getTime()/1E3|0},y:function(a){Q.mb(a)},
x:function(a){Q.release(a)},ta:function(a,b,c){a=T.get(a);b=X.get(b);c=X.get(c);c=a.add(b,c);return X.create(c)},sa:function(a,b,c){a=T.get(a);b=X.get(b);c=Oa(c);c=a.averagePool2d(b,c);return X.create(c)},ra:function(a,b,c,e,h){a=T.get(a);b=X.get(b);c=X.get(c);e=X.get(e);h={scale:X.get(G[h>>2]),bias:X.get(G[h+4>>2]),axis:G[h+8>>2],epsilon:J[h+12>>2],activation:Y.get(G[h+16>>2])};h=a.batchNormalization(b,c,e,h);return X.create(h)},qa:function(a,b){a=T.get(a);b=W.get(b);try{var c=a.build(b);return S.create(c)}catch(e){return console.log("builder.build failed: "+
e),0}},pa:function(a,b,c){a=T.get(a);b=X.get(b);c=a.clamp(b,{minValue:J[c>>2],maxValue:J[c+4>>2]});return X.create(c)},oa:function(a,b,c,e){a=T.get(a);b=P(b,c);c=[];for(var h=0;h<b.length;++h)c.push(X.get(b[h]));e=a.concat(c,e);return X.create(e)},na:function(a,b,c){a=T.get(a);b=Na(b);c=Ma(c,b.type);c=void 0===b.dimensions?a.constant(c[0]):a.constant(b,c);return X.create(c)},ma:function(a,b,c,e){a=T.get(a);b=X.get(b);c=X.get(c);e={padding:"explicit"===Ia[G[e+40>>2]]?P(H[e>>2],G[e+4>>2]):void 0,strides:P(H[e+
8>>2],G[e+12>>2]),dilations:P(H[e+16>>2],G[e+20>>2]),autoPad:Ia[G[e+40>>2]],groups:G[e+48>>2],inputLayout:Ka[G[e+52>>2]],filterLayout:Ja[G[e+56>>2]],bias:X.get(G[e+60>>2]),activation:Y.get(G[e+64>>2])};e=a.conv2d(b,c,e);return X.create(e)},la:function(a,b,c,e){a=T.get(a);b=X.get(b);c=X.get(c);e={c:X.get(G[e>>2]),alpha:J[e+4>>2],beta:J[e+8>>2],aTranspose:0!==F[e+12>>0],bTranspose:0!==F[e+13>>0]};e=a.gemm(b,c,e);return X.create(e)},ka:function(a,b,c){a=T.get(a);b=D(b);c=Na(c);c=a.input(b,c);return X.create(c)},
ja:function(a,b,c){a=T.get(a);b=X.get(b);c=a.leakyRelu(b,{alpha:J[c>>2]});return X.create(c)},ia:function(a,b){a=T.get(a).leakyRelu({alpha:J[b>>2]});return Y.create(a)},ha:function(a,b,c){a=T.get(a);b=X.get(b);c=X.get(c);c=a.matmul(b,c);return X.create(c)},ga:function(a,b,c){a=T.get(a);b=X.get(b);c=Oa(c);c=a.maxPool2d(b,c);return X.create(c)},u:function(a){T.release(a)},fa:function(a,b){a=T.get(a);b=X.get(b);b=a.relu(b);return X.create(b)},ea:function(a){a=T.get(a).relu();return Y.create(a)},da:function(a,
b,c,e){a=T.get(a);b=X.get(b);c=P(e,c);c=a.reshape(b,c);return X.create(c)},va:function(a,b,c){a=S.get(a);b=U.get(b);c=V.get(c);return a.compute(b,c)},ua:function(a){S.mb(a)},w:function(a){S.release(a)},aa:function(a){U.release(a)},ba:function(a,b,c){a=U.get(a);b=D(b);c=0===G[c+12>>2]?Ma(c+0):{resource:Ma(c+0),dimensions:P(H[c+16>>2],G[c+12>>2])};a[b]=c},_:function(a){W.release(a)},$:function(a,b,c){a=W.get(a);b=D(b);c=X.get(c);a[b]=c},Y:function(a){V.release(a)},Z:function(a,b,c){a=V.get(a);b=D(b);
c=Ma(c);a[b]=c},e:function(a){X.mb(a)},d:function(a){X.release(a)},X:function(a){Y.mb(a)},h:function(a){Y.release(a)},xa:eb,g:function(a,b,c,e){return eb(a,b,c,e)},W:function(a){a=Q.get(a);a=new MLGraphBuilder(a);return T.create(a)},V:function(){return U.create({})},U:function(){return W.create({})},T:function(){return V.create({})}};
(function(){function a(h){d.asm=h.exports;ia=d.asm.Ba;ra();sa=d.asm.fb;ua.unshift(d.asm.Ca);K--;d.monitorRunDependencies&&d.monitorRunDependencies(K);0==K&&(null!==ya&&(clearInterval(ya),ya=null),L&&(h=L,L=null,h()))}function b(h){a(h.instance)}function c(h){return Ca().then(function(k){return WebAssembly.instantiate(k,e)}).then(h,function(k){B("failed to asynchronously prepare wasm: "+k);A(k)})}var e={a:jb};K++;d.monitorRunDependencies&&d.monitorRunDependencies(K);if(d.instantiateWasm)try{return d.instantiateWasm(e,
a)}catch(h){return B("Module.instantiateWasm callback failed with error: "+h),!1}(function(){return C||"function"!==typeof WebAssembly.instantiateStreaming||za()||M.startsWith("file://")||"function"!==typeof fetch?c(b):fetch(M,{credentials:"same-origin"}).then(function(h){return WebAssembly.instantiateStreaming(h,e).then(b,function(k){B("wasm streaming compile failed: "+k);B("falling back to ArrayBuffer instantiation");return c(b)})})})().catch(ba);return{}})();
d.___wasm_call_ctors=function(){return(d.___wasm_call_ctors=d.asm.Ca).apply(null,arguments)};d._OrtInit=function(){return(d._OrtInit=d.asm.Da).apply(null,arguments)};d._OrtCreateSessionOptions=function(){return(d._OrtCreateSessionOptions=d.asm.Ea).apply(null,arguments)};d._OrtSessionOptionsAppendExecutionProviderWebNN=function(){return(d._OrtSessionOptionsAppendExecutionProviderWebNN=d.asm.Fa).apply(null,arguments)};
d._OrtAddSessionConfigEntry=function(){return(d._OrtAddSessionConfigEntry=d.asm.Ga).apply(null,arguments)};d._OrtReleaseSessionOptions=function(){return(d._OrtReleaseSessionOptions=d.asm.Ha).apply(null,arguments)};d._OrtCreateSession=function(){return(d._OrtCreateSession=d.asm.Ia).apply(null,arguments)};d._OrtReleaseSession=function(){return(d._OrtReleaseSession=d.asm.Ja).apply(null,arguments)};d._OrtGetInputCount=function(){return(d._OrtGetInputCount=d.asm.Ka).apply(null,arguments)};
d._OrtGetOutputCount=function(){return(d._OrtGetOutputCount=d.asm.La).apply(null,arguments)};d._OrtGetInputName=function(){return(d._OrtGetInputName=d.asm.Ma).apply(null,arguments)};d._OrtGetOutputName=function(){return(d._OrtGetOutputName=d.asm.Na).apply(null,arguments)};d._OrtFree=function(){return(d._OrtFree=d.asm.Oa).apply(null,arguments)};d._OrtCreateTensor=function(){return(d._OrtCreateTensor=d.asm.Pa).apply(null,arguments)};
d._OrtGetTensorData=function(){return(d._OrtGetTensorData=d.asm.Qa).apply(null,arguments)};d._OrtReleaseTensor=function(){return(d._OrtReleaseTensor=d.asm.Ra).apply(null,arguments)};d._OrtCreateRunOptions=function(){return(d._OrtCreateRunOptions=d.asm.Sa).apply(null,arguments)};d._OrtAddRunConfigEntry=function(){return(d._OrtAddRunConfigEntry=d.asm.Ta).apply(null,arguments)};d._OrtReleaseRunOptions=function(){return(d._OrtReleaseRunOptions=d.asm.Ua).apply(null,arguments)};
d._OrtRun=function(){return(d._OrtRun=d.asm.Va).apply(null,arguments)};d._OrtEndProfiling=function(){return(d._OrtEndProfiling=d.asm.Wa).apply(null,arguments)};
var pa=d._malloc=function(){return(pa=d._malloc=d.asm.Xa).apply(null,arguments)},ib=d.___errno_location=function(){return(ib=d.___errno_location=d.asm.Ya).apply(null,arguments)},hb=d._free=function(){return(hb=d._free=d.asm.Za).apply(null,arguments)},Z=d.__get_tzname=function(){return(Z=d.__get_tzname=d.asm._a).apply(null,arguments)},Wa=d.__get_daylight=function(){return(Wa=d.__get_daylight=d.asm.$a).apply(null,arguments)},Va=d.__get_timezone=function(){return(Va=d.__get_timezone=d.asm.ab).apply(null,
arguments)},kb=d.stackSave=function(){return(kb=d.stackSave=d.asm.bb).apply(null,arguments)},lb=d.stackRestore=function(){return(lb=d.stackRestore=d.asm.cb).apply(null,arguments)},mb=d.stackAlloc=function(){return(mb=d.stackAlloc=d.asm.db).apply(null,arguments)},gb=d._memalign=function(){return(gb=d._memalign=d.asm.eb).apply(null,arguments)};d.UTF8ToString=D;d.stringToUTF8=function(a,b,c){return ma(a,E,b,c)};d.lengthBytesUTF8=na;d.stackSave=kb;d.stackRestore=lb;d.stackAlloc=mb;var nb;
L=function ob(){nb||pb();nb||(L=ob)};
function pb(){function a(){if(!nb&&(nb=!0,d.calledRun=!0,!ja)){Da(ua);aa(d);if(d.onRuntimeInitialized)d.onRuntimeInitialized();if(d.postRun)for("function"==typeof d.postRun&&(d.postRun=[d.postRun]);d.postRun.length;){var b=d.postRun.shift();wa.unshift(b)}Da(wa)}}if(!(0<K)){if(d.preRun)for("function"==typeof d.preRun&&(d.preRun=[d.preRun]);d.preRun.length;)xa();Da(ta);0<K||(d.setStatus?(d.setStatus("Running..."),setTimeout(function(){setTimeout(function(){d.setStatus("")},1);a()},1)):a())}}d.run=pb;
if(d.preInit)for("function"==typeof d.preInit&&(d.preInit=[d.preInit]);0<d.preInit.length;)d.preInit.pop()();pb();


  return ortWasm.ready
}
);
})();
if (typeof exports === 'object' && typeof module === 'object')
  module.exports = ortWasm;
else if (typeof define === 'function' && define['amd'])
  define([], function() { return ortWasm; });
else if (typeof exports === 'object')
  exports["ortWasm"] = ortWasm;
